#!/usr/bin/env bash

# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

changed() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

if changed 'package.lock'; then 
	echo "[package.lock] changed: Installing npm dependencies..."
	if [ "$(whoami)" == "gitlab" ]; 
	then
		echo "executing npm ci..."
        npm ci
	else 
		echo "executing npm install..."
		npm install
	fi
fi